### ISSUE TITLE
Bug: Pressing Home from the Assignments screen takes you back to the login page

### ISSUE THREAD

**Issue by cassowarii** [terabyte128/HomeworkPlanner#1]
Maybe it's just me, but when I press the home button in the upper left of the assignments page, it takes me all the way back to the login page. If I try to log in again, it just says "Error loading page."

**Comment by cassowarii** [comment]
Actually, it might have just been me, because it seems to be working now. Chalk it up to jQuery Mobile weirdness, I guess.

**Comment by terabyte128** [comment]
Yes, it has to do with jquery mobile caching the login page, which is at the same URL as the homepage, so when you first login and go back it takes you to the login page. This can be fixed by passing a param not to cache the page.

**Comment by terabyte128** [comment]
@broomweed lol this is still broken but idc because i'm planning on rewriting this at some point in the near future, it will be bigger, faster, better, sexier, etc.

**Comment by cassowarii** [comment]
hahaha, OK
